import PostsList from './PostsList';
import App from './App';
import Navbar from './Navbar';
import Home from './Home';
import Page404 from './Page404';
import Login from './Login';
import Signup from './Signup';
import Settings from './Setting';
import UserProfile from './UserProfile';
import CreatePost from './CreatePost';
import Posts from './Posts';
import Comment from './Comment';
export { Comment,Posts,CreatePost,UserProfile,Settings,PostsList, App, Navbar, Home, Page404, Login, Signup };
